apiVersion: v1
kind: Service
metadata:
  name: two-rooms-boom
  labels:
    app: two-rooms-boom
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
    nodePort: 32121
  selector:
    app: two-rooms-boom
